Hw1
andrey-dru-me1/java-backend-course-2023 pull request #1
Opened 2023-10-15 15:41 UTC by andrey-dru-me1

2023-10-16 21:04 UTC, infomouse requested changes

2023-10-16 21:04 UTC, infomouse commented on src/main/java/edu/hw1/Task1.java
> +    public static int minutesToSeconds(@NotNull String string) {
minutesToSeconds("1:00") возвращает -1.

2023-10-16 21:04 UTC, infomouse commented on src/main/java/edu/hw1/Task2.java
> +    public static int countDigits(int number) {
countDigits(Integer.MIN_VALUE) возвращает 1.
Всегда надо делать тесты на граничные значения.

2023-10-16 21:04 UTC, infomouse commented on src/main/java/edu/hw1/Task3.java
> +    private static int arrMax(int @NotNull [] a) {
Зачем тут NotNull?

2023-10-16 21:04 UTC, infomouse commented on src/main/java/edu/hw1/Task4.java
> +    @Contract("_ -> new") public static @NotNull String fixString(@NotNull String str) {
Зачем тут аннотация Contract?

2023-10-16 21:04 UTC, infomouse commented on src/main/java/edu/hw1/Task5.java
> +    public static boolean isPalindromeDescendant(int number) {
isPalindromeDescendant(1) возвращает false, хотя это палиндром.

2023-10-16 21:04 UTC, infomouse commented on src/main/java/edu/hw1/Task6.java
> +    public static int countK(int fourDigitNumber) {
countK(1111) кидает StackOverflowError.

2023-10-16 21:04 UTC, infomouse commented on src/main/java/edu/hw1/Task1.java
> +        for (char p : "23:59".toCharArray()) {
А вы точно правильно поняли условие задачи?

2023-10-17 10:03 UTC, andrey-dru-me1 commented on src/main/java/edu/hw1/Task6.java
> +    public static int countK(int fourDigitNumber) {
Добавил IllegalArgumentException на некорректные аргументы https://github.com/andrey-dru-me1/java-backend-course-2023/pull/1/commits/31619a9fc62a5a39ac1169ad145cb4706e370462

2023-10-17 10:05 UTC, andrey-dru-me1 commented on src/main/java/edu/hw1/Task1.java
> +        for (char p : "23:59".toCharArray()) {
Да, я невнимательно по-началу прочитал...
Исправил, теперь принимает любое неотрицательное количество минут https://github.com/andrey-dru-me1/java-backend-course-2023/pull/1/commits/41cf4441fb6ae081506224dea002a826d2d45a58

2023-10-17 10:06 UTC, andrey-dru-me1 commented on src/main/java/edu/hw1/Task5.java
> +    public static boolean isPalindromeDescendant(int number) {
Добавил проверку этого условия https://github.com/andrey-dru-me1/java-backend-course-2023/pull/1/commits/d0375b7bbeec07f5a202abec9e68ba06b4b073de

2023-10-17 10:08 UTC, andrey-dru-me1 commented on src/main/java/edu/hw1/Task4.java
> +    @Contract("_ -> new") public static @NotNull String fixString(@NotNull String str) {
Думал, что рекомендуется при создании нового объекта оставлять подобную аннотацию. Убрал https://github.com/andrey-dru-me1/java-backend-course-2023/pull/1/commits/c81c0fb5b4d8e56cb4e235053f2204420ae4bff2

2023-10-17 10:09 UTC, andrey-dru-me1 commented on src/main/java/edu/hw1/Task3.java
> +    private static int arrMax(int @NotNull [] a) {
Intellij Idea рекомендует проставлять.
Убрал https://github.com/andrey-dru-me1/java-backend-course-2023/pull/1/commits/d66efabfdb80625af68fcedd71047fa5a3c72593

2023-10-17 10:12 UTC, andrey-dru-me1 commented on src/main/java/edu/hw1/Task2.java
> +    public static int countDigits(int number) {
Да-а, у меня там в принципе не обрабатывались никак отрицательные числа 😬
Исправил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/1/commits/0903ea568a7ec8ab53f03c30b33008e7ea700ef3

2023-10-17 10:13 UTC, andrey-dru-me1 commented on src/main/java/edu/hw1/Task1.java
> +    public static int minutesToSeconds(@NotNull String string) {
У меня там был строгий формат, что минуты записываются ровно двумя цифрами. Перечитал задание, исправил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/1/commits/41cf4441fb6ae081506224dea002a826d2d45a58

2023-10-17 20:37 UTC, infomouse commented on src/main/java/edu/hw1/Task1.java
> +            seconds += minutes * 60;
При арифметических операциях надо помнить о переполнении. minutesToSecond(Integer.MAX_VALUE + ":00") вернет -60.

2023-10-17 20:37 UTC, infomouse commented on src/main/java/edu/hw1/Task3.java
> +    private static int arrMax(int @NotNull [] a) {
Лучше не ставить аннотации, если не понимаете для чего они.

2023-10-17 20:40 UTC, infomouse approved these changes

2023-10-18 05:21 UTC, andrey-dru-me1 commented on src/main/java/edu/hw1/Task1.java
> +            seconds += minutes * 60;
Исправил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/1/commits/ea4bf7d05a46c7320c71ce503ed2f472d4704d4a

2023-10-18 05:21 UTC, merged