Hw2
andrey-dru-me1/java-backend-course-2023 pull request #2
Opened 2023-10-19 16:41 UTC by andrey-dru-me1

2023-10-20 18:25 UTC, infomouse requested changes

2023-10-20 18:25 UTC, infomouse commented on src/main/java/edu/hw2/task2/Rectangle.java
> +  @Contract("_ -> new")
Зачем тут аннотация Contract?

2023-10-20 18:25 UTC, infomouse commented on src/main/java/edu/hw2/task3/connection/FaultyConnection.java
> +      throw new ConnectionException();
Хорошей практикой считается при бросании исключений писать message.

2023-10-20 18:25 UTC, infomouse commented on src/main/java/edu/hw2/task1/Addition.java
> +  @Override
В джаве принято делать отступ в 4 пробела.
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2023-10-20 18:25 UTC, infomouse commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +  void tryExecute(String command) {
Не выполнено требование:
Если tryExecute не смог выполнить команду (превышено количество попыток), то нужно вернуть ConnectionException, при этом сохранив оригинальное исключение в параметре cause

2023-10-20 18:25 UTC, infomouse commented on src/test/java/edu/hw2/Task3Test.java
> +class Task3Test {
Нет негативных тестов.

2023-10-20 18:25 UTC, infomouse commented on src/test/java/edu/hw2/Task4Test.java
> +    assertThat(callingInfo.className()).isEqualTo(CallingInfo.class.getName());
В задаче требуется, чтобы вернулся CallingInfo("Task4Test", "test").

2023-10-22 19:21 UTC, andrey-dru-me1 commented on src/main/java/edu/hw2/task1/Addition.java
> +  @Override
Исправил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/2/commits/f95e3de69851e9e7d281ae4b72ec7cdc92ed35ed

2023-10-22 19:21 UTC, andrey-dru-me1 commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +  void tryExecute(String command) {
Исправил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/2/commits/cb70abe036c29cdc695eaf58f91759ffc2f28c05

2023-10-22 19:21 UTC, andrey-dru-me1 commented on src/main/java/edu/hw2/task3/connection/FaultyConnection.java
> +      throw new ConnectionException();
Добавил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/2/commits/cb70abe036c29cdc695eaf58f91759ffc2f28c05

2023-10-22 19:22 UTC, andrey-dru-me1 commented on src/main/java/edu/hw2/task2/Rectangle.java
> +  @Contract("_ -> new")
Убрал https://github.com/andrey-dru-me1/java-backend-course-2023/pull/2/commits/20d28b24b9e6633e6394fce0a1cb0ced0dd7cfaf

2023-10-22 19:22 UTC, andrey-dru-me1 commented on src/test/java/edu/hw2/Task4Test.java
> +    assertThat(callingInfo.className()).isEqualTo(CallingInfo.class.getName());
Исправил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/2/commits/da571dd3268ad2ee3e831e3bb2ffd90499a420f5

2023-10-22 20:20 UTC, andrey-dru-me1 commented on src/test/java/edu/hw2/Task3Test.java
> +class Task3Test {
Добавил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/2/commits/22ca00198bce01ebd4d7bcc1c3c745654df04656

2023-10-23 17:42 UTC, infomouse approved these changes

2023-10-23 17:42 UTC, infomouse commented on src/main/java/edu/hw2/task2/Rectangle.java
> +    @Contract("_ -> new")
Зачем тут аннотация Contract?

2023-10-23 17:42 UTC, infomouse commented on src/test/java/edu/hw2/Task3Test.java
> +    void test() {
На будущее: каждый тест должен проверять только одно требование. Если тест будет падать, то должно быть по названию сразу понятно какое требование не выполнено. В данном тесте у вас 3 разных проверки.

2023-10-24 05:57 UTC, andrey-dru-me1 commented on src/main/java/edu/hw2/task2/Rectangle.java
> +    @Contract("_ -> new")
Убрал

2023-10-24 05:58 UTC, merged