Project1
andrey-dru-me1/java-backend-course-2023 pull request #3
Opened 2023-10-22 20:51 UTC by andrey-dru-me1

2023-10-25 22:40 UTC, infomouse requested changes

2023-10-25 22:40 UTC, infomouse commented on src/main/java/edu/project1/ConsoleHangman.java
> +        System.out.println(start(Dictionary.getRandomWord(), ATTEMPT_AMOUNT) == Result.WIN ? "You won!" : "You lost.");
"Размазали" код. Метод main должен просто запускать класс игры и не должен содержать логики.

2023-10-25 22:40 UTC, infomouse commented on src/main/java/edu/project1/Dictionary.java
> +    public static String getRandomWord() {
Статические метода используются для функций без состояний. У вас же тут внутренний массив слов. Да и хотелось бы иметь возможность заменять слова без изменения кода словаря.

2023-10-25 22:40 UTC, infomouse commented on src/main/java/edu/project1/ConsoleHangman.java
> +    public static void main(String[] args) {
Такие методы лучше выносить в отдельный класс, например, GameRunner.

2023-10-25 22:40 UTC, infomouse commented on src/main/java/edu/project1/ConsoleHangman.java
> +    public static Result start(String wordToGuess, int maxMistakes) {
По-хорошему тут не должно быть статика, потому что у класса есть состояния scanner, word и тд. Но они почему-то в методе, такой подход сильно усложняет расширение логики.

2023-10-26 12:55 UTC, andrey-dru-me1 commented on src/main/java/edu/project1/ConsoleHangman.java
> +    public static Result start(String wordToGuess, int maxMistakes) {
Исправил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/3/commits/8f63b4b33a9d09dc692761268521d4e0039f02e5

2023-10-26 12:55 UTC, andrey-dru-me1 commented on src/main/java/edu/project1/ConsoleHangman.java
> +    public static void main(String[] args) {
Исправил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/3/commits/8f63b4b33a9d09dc692761268521d4e0039f02e5

2023-10-26 12:56 UTC, andrey-dru-me1 commented on src/main/java/edu/project1/Dictionary.java
> +    public static String getRandomWord() {
Убрал статику https://github.com/andrey-dru-me1/java-backend-course-2023/pull/3/commits/8f63b4b33a9d09dc692761268521d4e0039f02e5

2023-10-26 12:56 UTC, andrey-dru-me1 commented on src/main/java/edu/project1/ConsoleHangman.java
> +        System.out.println(start(Dictionary.getRandomWord(), ATTEMPT_AMOUNT) == Result.WIN ? "You won!" : "You lost.");
Исправил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/3/commits/8f63b4b33a9d09dc692761268521d4e0039f02e5

2023-10-29 20:19 UTC, infomouse approved these changes

2023-10-29 20:19 UTC, infomouse commented on src/main/java/edu/project1/GameRunner.java
> +        new ConsoleHangman(new Dictionary(new String[]{"Hello", "Security", "Socket", "Connection"}).getRandomWord(),
Тяжело читать такие однострочники. Лучше избегать создание и вызов метода в одной строке.
```java
        Dictionary dictionary = new Dictionary(new String[] {"Hello", "Security", "Socket", "Connection"});
        Scanner scanner = new Scanner(System.in);
        ConsoleHangman consoleHangman = new ConsoleHangman(dictionary.getRandomWord(), MAX_ATTEMPTS, scanner);
        consoleHangman.start();
```

2023-11-04 18:36 UTC, andrey-dru-me1 commented on src/main/java/edu/project1/GameRunner.java
> +        new ConsoleHangman(new Dictionary(new String[]{"Hello", "Security", "Socket", "Connection"}).getRandomWord(),
Исправил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/3/commits/fef58fe33d2165d3e98b6a68739de21c94639f15

2023-11-04 18:37 UTC, merged