Hw3
andrey-dru-me1/java-backend-course-2023 pull request #4
Opened 2023-10-29 15:48 UTC by andrey-dru-me1

2023-11-01 19:09 UTC, infomouse requested changes

2023-11-01 19:09 UTC, infomouse commented on src/main/java/edu/hw3/Task2.java
> +                throw new IllegalArgumentException();
Хорошая практика кидать исключение с более детальным описанием. Предлагаю ее придерживаться.

2023-11-01 19:09 UTC, infomouse commented on src/main/java/edu/hw3/Task3.java
> +        Map<T, Integer> res = new HashMap<>();
Не надо экономить буквы, это ухудшает читаемость. Лучше писать result.

2023-11-01 19:09 UTC, infomouse commented on src/main/java/edu/hw3/Task4.java
> +        if (!(num > 0 && num < 4000)) {
Если есть возможность написать условие без отрицания, то лучше это делать. Такое легче воспринимать.

2023-11-01 19:09 UTC, infomouse commented on src/main/java/edu/hw3/Task5.java
> +    public static Object[] parseContacts(String[] contacts, String ordering) {
В задании подразумевалось, что вы сделаете объект Contact(firstName, LastName) и будете возвращать массив таких объектов.

2023-11-04 18:46 UTC, andrey-dru-me1 commented on src/main/java/edu/hw3/Task2.java
> +                throw new IllegalArgumentException();
Добавил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/4/commits/3544bcf5e7e5164b20c91d280ec1813a11ba5fec

2023-11-04 18:46 UTC, andrey-dru-me1 commented on src/main/java/edu/hw3/Task2.java
> +                throw new IllegalArgumentException();
Добавил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/4/commits/3544bcf5e7e5164b20c91d280ec1813a11ba5fec

2023-11-04 18:50 UTC, andrey-dru-me1 commented on src/main/java/edu/hw3/Task3.java
> +        Map<T, Integer> res = new HashMap<>();
Обычно так и стараюсь именовать, но начал сталкиваться с тем, что некоторые имена становятся уже слишком болшими, так что за их громоздкостью уже сложно найти вызываемые методы. Но здесь не тот случай, согласен
Исправил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/4/commits/08352b6065dadd0076b54dcd0422dcca9f0a0b41

2023-11-04 18:53 UTC, andrey-dru-me1 commented on src/main/java/edu/hw3/Task4.java
> +        if (!(num > 0 && num < 4000)) {
Думал наоборот лучше описать удовлетворительный интервал в коде, а потом уже на него навесить отрицание, которое можно во-литературному считать как "Введённое значение не входит в допустимый интервал", но в вашем случае получается меньше логических операций.
Исправил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/4/commits/e5a7d87c5e51cf2a76bf6f645c2e0b4ac55caf84

2023-11-04 19:30 UTC, andrey-dru-me1 commented on src/main/java/edu/hw3/Task5.java
> +    public static Object[] parseContacts(String[] contacts, String ordering) {
Да, не понял по формулировке)
Добавил https://github.com/andrey-dru-me1/java-backend-course-2023/pull/4/commits/255ea9b745e5f795e078f09496cece3887289eb3

2023-11-18 08:01 UTC, merged