Hw4
andrey-dru-me1/java-backend-course-2023 pull request #5
Opened 2023-11-04 22:12 UTC by andrey-dru-me1

2023-11-14 08:16 UTC, infomouse requested changes

2023-11-14 08:16 UTC, infomouse commented on src/main/java/edu/hw4/HW4.java
> +        return animals.stream().sorted(Comparator.comparing(Animal::age).reversed()).toList().get(k - 1);
При пустом списке будет IndexOutOfBoundsException.

2023-11-14 08:16 UTC, infomouse commented on src/main/java/edu/hw4/HW4.java
> +    public static Animal task18(List<List<Animal>> animalLists) {
Попробуйте сделать через flatMap. Комментарий не влияет на баллы.

2023-11-18 08:26 UTC, andrey-dru-me1 commented on src/main/java/edu/hw4/HW4.java
> +    public static Animal task18(List<List<Animal>> animalLists) {
Исправил на flatMap https://github.com/andrey-dru-me1/java-backend-course-2023/pull/5/commits/26878c7a9221b783862c22aa7f96b5aa9a260cba

2023-11-18 08:32 UTC, andrey-dru-me1 commented on src/main/java/edu/hw4/HW4.java
> +        return animals.stream().sorted(Comparator.comparing(Animal::age).reversed()).toList().get(k - 1);
Да, будет... Так и нормальное же поведение, разве нет? Если на вход подаётся 0 животных и требуется найти первое самое старое, то запрос некорректен, и можно исключение выкинуть... То же самое, если передать 6 животных и запросить 7-ое старое или -15-ое

2023-11-18 08:35 UTC, andrey-dru-me1 commented on src/main/java/edu/hw4/HW4.java
> +        return animals.stream().sorted(Comparator.comparing(Animal::age).reversed()).toList().get(k - 1);
А что предполагается, если не исключение? Вернуть `null`? Или просто другое исключение из разряда `IllegalArgumentException`?

2023-11-26 20:47 UTC, andrey-dru-me1 commented on src/main/java/edu/hw4/HW4.java
> +        return animals.stream().sorted(Comparator.comparing(Animal::age).reversed()).toList().get(k - 1);
Поменял на NoSuchElementException 🤷‍♂

2023-12-10 17:20 UTC, merged